version: "3.7"

x-base_node: &base_node
    image: registry.corp.five.ai/visual-geometry/visual-geometry/ros-kinetic-desktop-full-xenial-benchmark:2.4
    ipc: host
    volumes: 
        - "/home/costin/projects/:/home/costin/projects/"
    stdin_open: true # docker run -i
    tty: true        # docker run -t

services:
    # define the nodes as copies of the base node
    node_1:
        << : *base_node
        container_name: node1
        hostname: node1
    
    node_2:
        << : *base_node
        container_name: node2
        hostname: node2

    node_3:
        << : *base_node
        container_name: node3
        hostname: node3

    node_4:
        << : *base_node
        container_name: node4
        hostname: node4

    node_5:
        << : *base_node
        container_name: node5
        hostname: node5

    node_6:
        << : *base_node
        container_name: node6
        hostname: node6
